# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from datayee.resources import asset_path

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1291, 843)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(asset_path("source/DataYee.ico"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 330, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton { color: black;}")
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(240, 0, 1021, 581))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(830, 640, 90, 51))
        self.leftButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(str(asset_path("source/left_arrow.ico"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon1)
        self.leftButton.setIconSize(QtCore.QSize(60, 60))
        self.leftButton.setObjectName("leftButton")
        self.lcslide = QtWidgets.QSlider(self.centralwidget)
        self.lcslide.setGeometry(QtCore.QRect(400, 630, 160, 22))
        self.lcslide.setMinimum(-50)
        self.lcslide.setMaximum(50)
        self.lcslide.setProperty("value", 0)
        self.lcslide.setTracking(True)
        self.lcslide.setOrientation(QtCore.Qt.Horizontal)
        self.lcslide.setObjectName("lcslide")
        self.lpslide = QtWidgets.QSlider(self.centralwidget)
        self.lpslide.setGeometry(QtCore.QRect(400, 680, 160, 22))
        self.lpslide.setMinimum(-20)
        self.lpslide.setMaximum(20)
        self.lpslide.setPageStep(10)
        self.lpslide.setProperty("value", 0)
        self.lpslide.setOrientation(QtCore.Qt.Horizontal)
        self.lpslide.setObjectName("lpslide")
        self.trashButtom = QtWidgets.QPushButton(self.centralwidget)
        self.trashButtom.setGeometry(QtCore.QRect(1200, 590, 71, 71))
        self.trashButtom.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(str(asset_path("source/trash.ico"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trashButtom.setIcon(icon2)
        self.trashButtom.setIconSize(QtCore.QSize(60, 60))
        self.trashButtom.setObjectName("trashButtom")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(240, 570, 1041, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(810, 580, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lcdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lcdoubleSpinBox.setGeometry(QtCore.QRect(320, 620, 70, 30))
        self.lcdoubleSpinBox.setDecimals(1)
        self.lcdoubleSpinBox.setSingleStep(0.5)
        self.lcdoubleSpinBox.setProperty("value", 1.0)
        self.lcdoubleSpinBox.setObjectName("lcdoubleSpinBox")
        self.lpdoubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.lpdoubleSpinBox.setGeometry(QtCore.QRect(320, 670, 70, 30))
        self.lpdoubleSpinBox.setMaximum(0.1)
        self.lpdoubleSpinBox.setSingleStep(0.005)
        self.lpdoubleSpinBox.setProperty("value", 0.01)
        self.lpdoubleSpinBox.setObjectName("lpdoubleSpinBox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 620, 41, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 670, 41, 31))
        self.label_3.setObjectName("label_3")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(790, 580, 16, 221))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(1170, 580, 20, 221))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1200, 670, 71, 71))
        self.pushButton_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(str(asset_path("source/renew.ico"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(60, 60))
        self.pushButton_2.setObjectName("pushButton_2")
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(1010, 640, 90, 51))
        self.rightButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(str(asset_path("source/right.ico"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon4)
        self.rightButton.setIconSize(QtCore.QSize(60, 60))
        self.rightButton.setObjectName("rightButton")
        self.topButton = QtWidgets.QPushButton(self.centralwidget)
        self.topButton.setGeometry(QtCore.QRect(920, 620, 91, 51))
        self.topButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(str(asset_path("source/top.ico"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.topButton.setIcon(icon5)
        self.topButton.setIconSize(QtCore.QSize(60, 60))
        self.topButton.setObjectName("topButton")
        self.downButton = QtWidgets.QPushButton(self.centralwidget)
        self.downButton.setGeometry(QtCore.QRect(920, 670, 91, 51))
        self.downButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(str(asset_path("source/down.ico"))), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon6)
        self.downButton.setIconSize(QtCore.QSize(60, 60))
        self.downButton.setObjectName("downButton")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(240, 790, 1031, 21))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.lclplabel = QtWidgets.QLabel(self.centralwidget)
        self.lclplabel.setGeometry(QtCore.QRect(240, 580, 401, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lclplabel.setFont(font)
        self.lclplabel.setText("")
        self.lclplabel.setObjectName("lclplabel")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(230, 580, 20, 211))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(1110, 650, 61, 31))
        self.spinBox.setMaximum(10000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName("spinBox")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(0, 70, 241, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(0, 190, 241, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 80, 201, 111))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tasktype_cell = QtWidgets.QRadioButton(self.groupBox_2)
        self.tasktype_cell.setGeometry(QtCore.QRect(10, 30, 201, 41))
        self.tasktype_cell.setObjectName("tasktype_cell")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 70, 161, 41))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 210, 191, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(100, 50, 21, 16))
        self.label_4.setObjectName("label_4")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_3.setGeometry(QtCore.QRect(120, 40, 51, 41))
        self.spinBox_3.setMaximum(40)
        self.spinBox_3.setProperty("value", 6)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setGeometry(QtCore.QRect(30, 40, 51, 41))
        self.spinBox_2.setMaximum(30)
        self.spinBox_2.setProperty("value", 1)
        self.spinBox_2.setObjectName("spinBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(640, 590, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 113, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 720, 16, 31))
        self.label_5.setObjectName("label_5")
        self.kSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.kSpinBox.setGeometry(QtCore.QRect(320, 720, 71, 31))
        self.kSpinBox.setDecimals(1)
        self.kSpinBox.setProperty("value", 1.0)
        self.kSpinBox.setObjectName("kSpinBox")
        self.kSlider = QtWidgets.QSlider(self.centralwidget)
        self.kSlider.setGeometry(QtCore.QRect(400, 730, 160, 22))
        self.kSlider.setMinimum(-20)
        self.kSlider.setMaximum(20)
        self.kSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kSlider.setObjectName("kSlider")
        self.usemodel_cb = QtWidgets.QCheckBox(self.centralwidget)
        self.usemodel_cb.setGeometry(QtCore.QRect(30, 10, 151, 21))
        self.usemodel_cb.setTristate(False)
        self.usemodel_cb.setObjectName("usemodel_cb")
        self.stickmodel = QtWidgets.QCheckBox(self.centralwidget)
        self.stickmodel.setGeometry(QtCore.QRect(30, 40, 151, 31))
        self.stickmodel.setObjectName("stickmodel")
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(640, 690, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.zoomx = QtWidgets.QCheckBox(self.groupBox_5)
        self.zoomx.setGeometry(QtCore.QRect(20, 40, 91, 19))
        self.zoomx.setObjectName("zoomx")
        self.zoomy = QtWidgets.QCheckBox(self.groupBox_5)
        self.zoomy.setGeometry(QtCore.QRect(80, 40, 91, 19))
        self.zoomy.setObjectName("zoomy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1291, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menuOpen = QtWidgets.QMenu(self.menu)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menuOpen.setFont(font)
        self.menuOpen.setStyleSheet("")
        self.menuOpen.setObjectName("menuOpen")
        self.menuExport = QtWidgets.QMenu(self.menu)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menuExport.setFont(font)
        self.menuExport.setObjectName("menuExport")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuEdit = QtWidgets.QMenu(self.menuBar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAction = QtWidgets.QMenu(self.menuEdit)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menuAction.setFont(font)
        self.menuAction.setObjectName("menuAction")
        self.menu_2 = QtWidgets.QMenu(self.menuEdit)
        self.menu_2.setObjectName("menu_2")
        self.menuPlot = QtWidgets.QMenu(self.menuBar)
        self.menuPlot.setObjectName("menuPlot")
        self.menucontour_lenght = QtWidgets.QMenu(self.menuPlot)
        self.menucontour_lenght.setGeometry(QtCore.QRect(0, 0, 166, 120))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menucontour_lenght.setFont(font)
        self.menucontour_lenght.setObjectName("menucontour_lenght")
        self.menuAdhesion = QtWidgets.QMenu(self.menuPlot)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.menuAdhesion.setFont(font)
        self.menuAdhesion.setObjectName("menuAdhesion")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionForce_Curve = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionForce_Curve.setFont(font)
        self.actionForce_Curve.setObjectName("actionForce_Curve")
        self.actionBatch_of_Force_Curve = QtWidgets.QAction(MainWindow)
        self.actionBatch_of_Force_Curve.setCheckable(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionBatch_of_Force_Curve.setFont(font)
        self.actionBatch_of_Force_Curve.setObjectName("actionBatch_of_Force_Curve")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actiontxt = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actiontxt.setFont(font)
        self.actiontxt.setObjectName("actiontxt")
        self.actionexcel = QtWidgets.QAction(MainWindow)
        self.actionexcel.setObjectName("actionexcel")
        self.actionCreate_methods = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionCreate_methods.setFont(font)
        self.actionCreate_methods.setObjectName("actionCreate_methods")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionUndo.setFont(font)
        self.actionUndo.setObjectName("actionUndo")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionhelp = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionhelp.setFont(font)
        self.actionhelp.setObjectName("actionhelp")
        self.actionDataYee = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionDataYee.setFont(font)
        self.actionDataYee.setObjectName("actionDataYee")
        self.actionDataYee_Force = QtWidgets.QAction(MainWindow)
        self.actionDataYee_Force.setObjectName("actionDataYee_Force")
        self.actionDelete = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.actionDelete.setFont(font)
        self.actionDelete.setObjectName("actionDelete")
        self.actionBaseline_plus = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionBaseline_plus.setFont(font)
        self.actionBaseline_plus.setObjectName("actionBaseline_plus")
        self.actionBaseline_minus = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionBaseline_minus.setFont(font)
        self.actionBaseline_minus.setObjectName("actionBaseline_minus")
        self.actionHistgram = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.actionHistgram.setFont(font)
        self.actionHistgram.setObjectName("actionHistgram")
        self.actionScatter = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.actionScatter.setFont(font)
        self.actionScatter.setObjectName("actionScatter")
        self.actionMap = QtWidgets.QAction(MainWindow)
        self.actionMap.setObjectName("actionMap")
        self.actionHistogram = QtWidgets.QAction(MainWindow)
        self.actionHistogram.setObjectName("actionHistogram")
        self.actionpeakindex_plus = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionpeakindex_plus.setFont(font)
        self.actionpeakindex_plus.setObjectName("actionpeakindex_plus")
        self.actionpeakindex_minus = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionpeakindex_minus.setFont(font)
        self.actionpeakindex_minus.setObjectName("actionpeakindex_minus")
        self.actionfigure = QtWidgets.QAction(MainWindow)
        self.actionfigure.setObjectName("actionfigure")
        self.actioncopy_peak = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actioncopy_peak.setFont(font)
        self.actioncopy_peak.setObjectName("actioncopy_peak")
        self.actionparameters_setting = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionparameters_setting.setFont(font)
        self.actionparameters_setting.setObjectName("actionparameters_setting")
        self.actionbatch_of_txt = QtWidgets.QAction(MainWindow)
        self.actionbatch_of_txt.setObjectName("actionbatch_of_txt")
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.actionForce_Curve)
        self.menuOpen.addAction(self.actionBatch_of_Force_Curve)
        self.menuOpen.addAction(self.actionDataYee_Force)
        self.menuExport.addAction(self.actiontxt)
        self.menuExport.addAction(self.actionexcel)
        self.menuExport.addAction(self.actionfigure)
        self.menuExport.addAction(self.actionbatch_of_txt)
        self.menu.addAction(self.menuOpen.menuAction())
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSave_as)
        self.menu.addAction(self.menuExport.menuAction())
        self.menu.addSeparator()
        self.menu.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionhelp)
        self.menuAbout.addAction(self.actionDataYee)
        self.menuAction.addAction(self.actionBaseline_plus)
        self.menuAction.addAction(self.actionBaseline_minus)
        self.menuAction.addAction(self.actionpeakindex_plus)
        self.menuAction.addAction(self.actionpeakindex_minus)
        self.menuAction.addAction(self.actioncopy_peak)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.actionparameters_setting)
        self.menuEdit.addAction(self.menuAction.menuAction())
        self.menuEdit.addAction(self.menu_2.menuAction())
        self.menucontour_lenght.addAction(self.actionHistgram)
        self.menucontour_lenght.addAction(self.actionScatter)
        self.menuAdhesion.addAction(self.actionMap)
        self.menuAdhesion.addAction(self.actionHistogram)
        self.menuPlot.addAction(self.menucontour_lenght.menuAction())
        self.menuPlot.addAction(self.menuAdhesion.menuAction())
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuPlot.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DataYee"))
        self.pushButton.setText(_translate("MainWindow", "Run"))
        self.groupBox.setTitle(_translate("MainWindow", "Force Curve"))
        self.label.setText(_translate("MainWindow", "Peak select:"))
        self.label_2.setText(_translate("MainWindow", "Lc"))
        self.label_3.setText(_translate("MainWindow", "Lp"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Task"))
        self.tasktype_cell.setText(_translate("MainWindow", "CELL CURVE"))
        self.radioButton_2.setText(_translate("MainWindow", "SMFS"))
        self.groupBox_3.setTitle(_translate("MainWindow", "PeakNum"))
        self.label_4.setText(_translate("MainWindow", "-"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Mark"))
        self.label_5.setText(_translate("MainWindow", "k"))
        self.usemodel_cb.setText(_translate("MainWindow", "USE MODEL"))
        self.stickmodel.setText(_translate("MainWindow", "Strick"))
        self.groupBox_5.setTitle(_translate("MainWindow", "ZOOM"))
        self.zoomx.setText(_translate("MainWindow", " X"))
        self.zoomy.setText(_translate("MainWindow", "Y"))
        self.menu.setTitle(_translate("MainWindow", "File"))
        self.menuOpen.setTitle(_translate("MainWindow", "Open"))
        self.menuExport.setTitle(_translate("MainWindow", "Export"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAction.setTitle(_translate("MainWindow", "Action"))
        self.menu_2.setTitle(_translate("MainWindow", "在这里输入"))
        self.menuPlot.setTitle(_translate("MainWindow", "Plot"))
        self.menucontour_lenght.setTitle(_translate("MainWindow", "contour lenght"))
        self.menuAdhesion.setTitle(_translate("MainWindow", "Adhesion"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionForce_Curve.setText(_translate("MainWindow", "Force Curve"))
        self.actionBatch_of_Force_Curve.setText(_translate("MainWindow", "Batch of Force Curve"))
        self.actionBatch_of_Force_Curve.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actiontxt.setText(_translate("MainWindow", "txt"))
        self.actionexcel.setText(_translate("MainWindow", "excel"))
        self.actionCreate_methods.setText(_translate("MainWindow", "Methods"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionhelp.setText(_translate("MainWindow", "help"))
        self.actionDataYee.setText(_translate("MainWindow", "DataYee"))
        self.actionDataYee_Force.setText(_translate("MainWindow", "DataYee-Force"))
        self.actionDelete.setText(_translate("MainWindow", "Delete"))
        self.actionDelete.setShortcut(_translate("MainWindow", "Del"))
        self.actionBaseline_plus.setText(_translate("MainWindow", "Baseline plus"))
        self.actionBaseline_plus.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionBaseline_minus.setText(_translate("MainWindow", "Baseline minus"))
        self.actionBaseline_minus.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionHistgram.setText(_translate("MainWindow", "Histogram"))
        self.actionScatter.setText(_translate("MainWindow", "Scatter"))
        self.actionMap.setText(_translate("MainWindow", "Map"))
        self.actionHistogram.setText(_translate("MainWindow", "Histogram"))
        self.actionpeakindex_plus.setText(_translate("MainWindow", "peakindex_plus"))
        self.actionpeakindex_plus.setShortcut(_translate("MainWindow", "+"))
        self.actionpeakindex_minus.setText(_translate("MainWindow", "peakindex_minus"))
        self.actionpeakindex_minus.setShortcut(_translate("MainWindow", "_"))
        self.actionfigure.setText(_translate("MainWindow", "figure"))
        self.actioncopy_peak.setText(_translate("MainWindow", "copy peak"))
        self.actioncopy_peak.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionparameters_setting.setText(_translate("MainWindow", "parameters setting"))
        self.actionparameters_setting.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionbatch_of_txt.setText(_translate("MainWindow", "batch of txt"))

