# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fittingEnergy.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fitting(object):
    def setupUi(self, fitting):
        fitting.setObjectName("fitting")
        fitting.resize(898, 680)
        self.gridLayout = QtWidgets.QGridLayout(fitting)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(fitting)
        self.graphicsView.setMinimumSize(QtCore.QSize(400, 0))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 3)
        self.tableWidget = QtWidgets.QTableWidget(fitting)
        self.tableWidget.setMinimumSize(QtCore.QSize(0, 400))
        self.tableWidget.setMaximumSize(QtCore.QSize(450, 16777215))
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setRowCount(15)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(fitting)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.gridLayout.addWidget(self.groupBox_2, 1, 2, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(fitting)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.argname = QtWidgets.QLabel(self.groupBox)
        self.argname.setMinimumSize(QtCore.QSize(50, 0))
        self.argname.setText("")
        self.argname.setObjectName("argname")
        self.horizontalLayout.addWidget(self.argname)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout.addWidget(self.doubleSpinBox_2)
        self.unit = QtWidgets.QLabel(self.groupBox)
        self.unit.setMinimumSize(QtCore.QSize(40, 0))
        self.unit.setText("")
        self.unit.setObjectName("unit")
        self.horizontalLayout.addWidget(self.unit)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)

        self.retranslateUi(fitting)
        QtCore.QMetaObject.connectSlotsByName(fitting)

    def retranslateUi(self, fitting):
        _translate = QtCore.QCoreApplication.translate
        fitting.setWindowTitle(_translate("fitting", "Energy landscape"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("fitting", "Force (pN)"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("fitting", "loading rate (pN/s)"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("fitting", "Calculate"))
        self.pushButton_2.setText(_translate("fitting", "Save"))
        self.label.setText(_translate("fitting", "-"))
        self.pushButton_3.setText(_translate("fitting", "next"))

